version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "parcel"
      - dependency-name: "@parcel/*"
      - dependency-name: "@defichain/*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/chore"
