version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    labels:
      - "kind/dependencies"
    ignore:
      - dependency-name: "@defichain/*"
      - dependency-name: "@react-native-async-storage/async-storage"
      - dependency-name: "@react-native-community/masked-view"
      - dependency-name: "@react-navigation/bottom-tabs"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-native"
      - dependency-name: "react-native-safe-area-context"
      - dependency-name: "react-native-screens"
      - dependency-name: "react-native-gesture-handler"
      - dependency-name: "react-native-svg"
      - dependency-name: "react-native-web"
      - dependency-name: "expo"
      - dependency-name: "@expo/*"
      - dependency-name: "expo-*"
      - dependency-name: "@babel/core"
      - dependency-name: "@types/react"
      - dependency-name: "@types/react-native"
      - dependency-name: "typescript"
      - dependency-name: "jest-expo"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "kind/chore"
