version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/assets
    sync: true
    matcher:
      files: "assets/**"

  - label: area/playground
    sync: true
    matcher:
      files: "playground/**"

  - label: area/translations
    sync: true
    matcher:
      files: "translations/**"

  - label: screen/BalancesScreen
    sync: true
    matcher:
      files: "screens/BalancesScreen/**"

  - label: screen/LiquidityScreen
    sync: true
    matcher:
      files: "screens/LiquidityScreen/**"

  - label: screen/SettingsScreen
    sync: true
    matcher:
      files: "screens/SettingsScreen/**"

  - label: screen/TransactionsScreen
    sync: true
    matcher:
      files: "screens/TransactionsScreen/**"
