version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/api
    sync: true
    matcher:
      files: "wallet-app/app/api/**"

  - label: area/assets
    sync: true
    matcher:
      files: "wallet-app/app/assets/**"

  - label: area/contexts
    sync: true
    matcher:
      files: "wallet-app/app/contexts/**"

  - label: area/hooks
    sync: true
    matcher:
      files: "wallet-app/app/hooks/**"

  - label: area/store
    sync: true
    matcher:
      files: "wallet-app/app/store/**"

  - label: area/translations
    sync: true
    matcher:
      files: "wallet-app/app/translations/**"

  - label: area/e2e
    sync: true
    matcher:
      files: "cypress/**"

  - label: area/ui-ux
    sync: true
    matcher:
      files:
        - "wallet-app/app/screens/**"
        - "wallet-app/app/components/**"

  - label: area/playground
    sync: true
    matcher:
      files: "wallet-app/app/screens/PlaygroundNavigator/**"
