version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/assets
    sync: true
    matcher:
      files: "assets/**"

  - label: area/playground
    sync: true
    matcher:
      files: "screens/PlaygroundNavigator/**"

  - label: area/translations
    sync: true
    matcher:
      files: "translations/**"

  - label: area/e2e
    sync: true
    matcher:
      files: "cypress/**"
