version: v1

labels:
  - label: area/workflow
    sync: true
    matcher:
      files: ".github/**"

  - label: area/assets
    sync: true
    matcher:
      files: "assets/**"

  - label: area/navigation
    sync: true
    matcher:
      files: "navigation/**"

  - label: area/playground
    sync: true
    matcher:
      files: "playground/**"

  - label: area/index
    sync: true
    matcher:
      files: "index/**"

  - label: screen/BalancesScreen
    sync: true
    matcher:
      files: "screen/BalancesScreen/**"

  - label: screen/LiquidityScreen
    sync: true
    matcher:
      files: "screen/LiquidityScreen/**"

  - label: screen/SettingsScreen
    sync: true
    matcher:
      files: "screen/SettingsScreen/**"

  - label: screen/TransactionsScreen
    sync: true
    matcher:
      files: "screen/TransactionsScreen/**"
