version: "2"

checks:
  similar-code:
    enabled: true
    config:
      threshold: 175
  method-lines:
    config:
      threshold: 100

exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/cypress/"
  - "**/shared/assets/"
  - "**/components/icons"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.d.ts"
