version: "2"

checks:
  similar-code:
    enabled: true
    config:
      threshold: 150
  method-lines:
    config:
      threshold: 50

exclude_patterns:
  - "dist/"
  - "**/node_modules/"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.d.ts"
