name: CI Drift

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tailwind:
    name: Tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97
      - uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: "Drift Detection: tailwind.config.js"
        working-directory: mobile-app/app
        run: |
          export BEFORE=$(openssl sha1 styles.json | sed 's/^.* //')
          npx create-tailwind-rn
          export AFTER=$(openssl sha1 styles.json | sed 's/^.* //')

          if [ "$BEFORE" != "$AFTER" ] ; then
            echo "Drift detected: tailwind.config.js, please run 'npx create-tailwind-rn' in the /app directory."
            exit 1
          fi
