name: CI Drift

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tailwind:
    name: Tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci

      - name: "Drift Detection: tailwind.config.js"
        run: |
          export BEFORE=$(openssl sha1 tailwind.json | sed 's/^.* //')
          npm run tailwind:build
          export AFTER=$(openssl sha1 tailwind.json | sed 's/^.* //')

          if [ "$BEFORE" != "$AFTER" ] ; then
            echo "Drift detected: tailwind.config.js, please run 'npm run tailwind:build' in the root directory."
            exit 1
          fi
