name: CI Drift

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tailwind:
    name: Tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 16
          cache: "npm"

      - run: npm ci

      - name: "Drift Detection: tailwind.config.js"
        working-directory: mobile-app/app
        run: |
          export BEFORE=$(openssl sha1 styles.json | sed 's/^.* //')
          npx create-tailwind-rn
          export AFTER=$(openssl sha1 styles.json | sed 's/^.* //')

          if [ "$BEFORE" != "$AFTER" ] ; then
            echo "Drift detected: tailwind.config.js, please run 'npx create-tailwind-rn' in the /app directory."
            exit 1
          fi
