name: Drift Detection

on:
  pull_request:
    branches: [ main ]

jobs:
  tailwind:
    name: Tailwind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@d6e3b5539ed7e5ccd26c3459e26c7c817f4e9068
        with:
          node-version: 15
          cache: 'npm'

      - run: npm ci

      - name: "Drift Detection: tailwind.config.js"
        working-directory: app
        run: |
          export BEFORE=$(openssl sha1 styles.json | sed 's/^.* //')
          npx create-tailwind-rn
          export AFTER=$(openssl sha1 styles.json | sed 's/^.* //')

          if [ "$BEFORE" != "$AFTER" ] ; then
            echo "Drift detected: tailwind.config.js, please run 'npx create-tailwind-rn' in the /app directory."
            exit 1
          fi
