name: Update iOS Provisioning Profile

on:
  workflow_dispatch:

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Authenticate with Expo and Sync iOS credentials
        run: |
          echo 'Authenticating with Expo...'
          export EXPO_TOKEN="${{ secrets.EXPO_TOKEN }}"
          export EXPO_APPLE_API_KEY_ID="${{ secrets.EXPO_APPLE_API_KEY_ID }}"
          export EXPO_APPLE_API_ISSUER_ID="${{ secrets.EXPO_APPLE_API_ISSUER_ID }}"
          export EXPO_APPLE_API_KEY="${{ secrets.EXPO_APPLE_API_KEY }}"
          npx eas-cli whoami || npx eas-cli login --non-interactive
          echo 'Syncing iOS credentials...'
          npx eas-cli credentials:sync --platform ios
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EXPO_APPLE_API_KEY_ID: ${{ secrets.EXPO_APPLE_API_KEY_ID }}
          EXPO_APPLE_API_ISSUER_ID: ${{ secrets.EXPO_APPLE_API_ISSUER_ID }}
          EXPO_APPLE_API_KEY: ${{ secrets.EXPO_APPLE_API_KEY }}
