name: Expo Main Preview

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: 16

      - uses: expo/expo-github-action@f98a64c8874c4a163514273f34306f403e962350 # tag=v7.2.0
        with:
          expo-version: latest
          eas-version: latest
          expo-cache: true
          eas-cache: true
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci
      - run: eas update --auto --branch main --message 'Update with commit ${{ github.sha }}'
        env:
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
