name: Expo

on:
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: actions/setup-node@56337c425554a6be30cdef71bf441f15be286854
        with:
          node-version: 16

      - uses: expo/expo-github-action@f98a64c8874c4a163514273f34306f403e962350
        with:
          expo-version: 4.x
          expo-cache: true
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci
      - run: expo publish --release-channel=main
