name: Expo

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: 15

      - uses: expo/expo-github-action@a888e4f3111809b703f2a1471dc7f1f3fc5cbfa8
        with:
          expo-version: 4.x
          expo-packager: npm
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - run: npm ci
      - run: expo publish
