name: Expo

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@38d90ce44d5275ad62cc48384b3d8a58c500bb5f
        with:
          node-version: 15

      - uses: expo/expo-github-action@c3c02de017ef8cf6152daee160e8a47a2340a5e5
        with:
          expo-version: 4.x
          expo-cache: true
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci
      - run: expo publish --release-channel=main
