name: Expo

on:
  push:
    branches: [ main ]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: 15

      - uses: expo/expo-github-action@c3c02de017ef8cf6152daee160e8a47a2340a5e5
        with:
          expo-version: 4.x
          expo-packager: npm
          expo-cache: true
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci
      - run: expo publish --release-channel=main
