name: Expo Main Preview

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 16

      - uses: expo/expo-github-action@4479f0b3692e25169fa71a02c30d6586ec2f5601 # tag=v7.2.0
        with:
          expo-version: latest
          eas-version: latest
          expo-cache: true
          eas-cache: true
          packager: npm
          token: ${{ secrets.EXPO_TOKEN }}

      - run: npm ci
      - run: eas update --auto --branch main --message 'Update with commit ${{ github.sha }}'
        env:
          EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
