name: Governance

on:
  pull_request_target:
    types: [ synchronize, opened, labeled, unlabeled ]
  issues:
    types: [ opened, labeled, unlabeled ]
  issue_comment:
    types: [ created ]

jobs:
  main:
    name: OSS
    runs-on: ubuntu-latest
    steps:
      - uses: BirthdayResearch/oss-governance-bot@23a023a59e633947923a299f0497371576e12e78
        with:
          github-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}

