name: Governance

on:
  issues:
    types: [ opened, labeled ]

jobs:
  main:
    name: DeFi Products
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'triage/accepted')
    steps:
      - uses: takanabe/github-actions-automate-projects@5d004c140c65fa8b4ef3b18a38219ce680bce816
        env:
          GITHUB_TOKEN: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          GITHUB_PROJECT_URL: https://github.com/orgs/DeFiCh/projects/1
          GITHUB_PROJECT_COLUMN_NAME: To do
