name: Governance

on:
  pull_request_target:
    types: [ opened ]

jobs:
  main:
    name: DeFi Products
    runs-on: ubuntu-latest
    if: github.event.sender.type == 'User' && github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - uses: actions/github-script@f891eff65186019cbb3f7190c4590bc0a1b76fbc
        with:
          github-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          script: |
            github.projects.createCard({
              column_id: 14389251,
              content_id: context.payload.pull_request.id,
              content_type: 'PullRequest',
            });

            github.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: [context.payload.sender.login]
            })
