name: Lint PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@e642fa0dddcbe4cd256f0c7f46e88c7f9906f637
        with:
          requireScope: true
          types: |
            fix
            feature
            chore
            docs
            style
            refactor
            perf
            test
            ci
            build
          scopes: |
            core
            workflow
            api
            assets
            contexts
            hooks
            store
            translations
            e2e
            unit-tests
            ui-ux
            playground
            website
            website-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
