name: Lint PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@c550c946d5e73d5310a5718997502b9f5a8e9e84
        with:
          subjectPattern: ^(?![A-Z]).+$
          validateSingleCommit: true
          requireScope: true
          types: |
            fix
            feature
            chore
            docs
            style
            refactor
            performance
            test
            ci
            build
          scopes: |
            core
            workflow
            api
            assets
            contexts
            hooks
            store
            translations
            e2e
            unit-tests
            ui-ux
            playground
            website
            website-api
            deps-dev
            deps
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
