name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@f551477c43766f7020024aa95f1074aeeb96a0bf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
