name: Publish

on:
  release:
    types: [ published, prereleased ]

jobs:
  publish:
    name: Publish
    environment: Expo Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: 15

      - uses: expo/expo-github-action@8275e8fa89e599e1b1ef793b0219c299f79bc32b
        with:
          expo-version: 4.x
          expo-packager: npm
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - run: npm ci

      - name: Publish Prerelease
        if: github.event.release.prerelease
        run: expo publish --release-channel=prerelease

      - name: Publish Release
        if: "!github.event.release.prerelease"
        run: expo publish --release-channel=production

  eas:
    name: EAS
    environment: EAS Release
    runs-on: ubuntu-latest
    if: "!github.event.release.prerelease"
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - uses: actions/setup-node@46071b5c7a2e0c34e49c3cb8a0e792e86e18d5ea
        with:
          node-version: 15

      - uses: expo/expo-github-action@8275e8fa89e599e1b1ef793b0219c299f79bc32b
        with:
          expo-version: 4.x
          expo-packager: npm
          expo-token: ${{ secrets.EXPO_TOKEN }}
          expo-cache: true

      - run: npm ci
      - run: npm install -g eas-cli

      - name: EAS Build
        run: eas build --platform all --non-interactive --wait

      - run: sleep 15s

      - name: EAS Submit (iOS)
        run: eas submit --platform ios --latest --asc-app-id ${{ secrets.ASC_APP_ID }} --apple-id ${{ secrets.APPLE_ID }}
        env:
          EXPO_APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.EXPO_APPLE_APP_SPECIFIC_PASSWORD }}

      - name: EAS Submit (Android)
        run: |
          echo "${{ secrets.ANDROID_SERVICE_ACCOUNT_JSON }}" > ANDROID_SERVICE_ACCOUNT.json
          eas submit --platform android --latest --key=ANDROID_SERVICE_ACCOUNT.json
