name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@fe52e97d262833ae07d05efaf1a239df3f1b5cd4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
