name: Release Drafter

on:
  push:
    branches: [ main ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@e9ee02fbac03d922bac6212003695e8358dd88b0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
