name: 'Close stale issues and PR'

on:
  schedule:
    - cron: '30 22 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@532554b8a8498a0e006fbcde824b048728c4178f
        with:
          repo-token: ${{ secrets.DEFICHAIN_BOT_GITHUB_TOKEN }}
          remove-stale-when-updated: true
          exempt-milestones: true
          exempt-assignees: true

          days-before-issue-stale: 40
          days-before-issue-close: 5
          exempt-issue-labels: 'triage/accepted,kind/feature,good first issue'
          stale-issue-message: "This issue is stale because it has been open for 40 days without any activity. Please remove the stale label or this will be closed in 5 days."
          stale-issue-label: "stale"

          days-before-pr-stale: 90
          days-before-pr-close: 14
          stale-pr-message: "This pull request is stale because it has been open for 90 days without any activity. Please remove the stale label or this will be closed in 14 days."
          stale-pr-label: "stale"
