name: Labels

on:
  push:
    branches: [ main ]
    paths: [ .github/labels.yml ]

jobs:
  main:
    name: Syncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - uses: micnncim/action-label-syncer@0e9c5104859d0e78219af63791636eba42382b5d
        with:
          prune: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
