name: Labels

on:
  push:
    branches: [ main ]
    paths: [ .github/labels.yml ]

jobs:
  main:
    name: Syncer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@dcd71f646680f2efd8db4afa5ad64fdcba30e748

      - uses: micnncim/action-label-syncer@0e9c5104859d0e78219af63791636eba42382b5d
        with:
          prune: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
